### ISSUE TITLE
ValidationError: CSS Loader Invalid Options

### ISSUE THREAD

**Issue by sfentress** [pinqy520/three-typescript-starter#5]
I'm unable to run the project from a clean install:

```
$ git clone https://github.com/pinqy520/three-typescript-starter.git
$ cd three-typescript-starter
$ npm install
$ npm start
...
ERROR in ./src/style.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./src/style.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties

    at validateOptions (/Users/samfentress/projects/three-typescript-starter/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.loader (/Users/samfentress/projects/three-typescript-starter/node_modules/css-loader/dist/index.js:34:28)
 @ ./src/style.css 2:14-87
 @ ./src/index.ts
 @ multi ./src/index.ts
```

**Comment by pinqy520** [comment]
fixed
